### PR TITLE
setup travis with php lint for 5.3-7.3

### PR DESCRIPTION
**Pull request by glensc**
setup travis-ci to prevent such mistakes like https://github.com/zf1s/zend-view/pull/2

### CODE REVIEW

**Comment by falkenhawk** [comment]
thanks, that's a good idea for now, but maybe we could avoid setting travis up in each repo? Since the original ZF had a single big test suite, maybe we should set up a separate repo just for tests - running a test suite there would install all zf1s packages and run all tests on all php versions. But that probably won't be automatically triggered on each pull request from an individual package repo...

**Comment by falkenhawk** [comment]
Also, it would be a chance to adjust the original test suite for php 7.x, as I am afraid they are not compatible...

**Comment by glensc** [comment]
seems step backwards and likely introduce new problems. if you worry about the overhead, then only do the travis setup when someone submits PR there. i.e packages that are actually modified.

**Comment by falkenhawk** [comment]
Yeah, the best way would be to separate original test suite by package and put them in corresponding repos...

**Comment by glensc** [comment]
removed WIP

**Comment by falkenhawk** [comment]
@glensc would you please take a look, if you have time, at https://github.com/zf1s/zend-view/pull/4 ? Anyway I could see a potential problem of testing just one component, since zf1 was quite tightly coupled, that rather full test suite should be run on each change. I am already trying by luck with merging all those zf1s packages into a monorepo... but tests should still be divided and moved into corresponding package folders to allow individual package testing

**Comment by glensc** [comment]
having monorepo, can still have single packages in composer? will the split out repos stay? the contribution would go via monorepo or split out repos?

**Comment by falkenhawk** [comment]
There will be single packages in composer, split repos will stay, but read-only and synced, the contribution would go via monorepo and synced later with split repos with a tool. I've spent too much time already adjusting tests, at least I don't have fatal errors anymore. Still some errors and failures to fix. I will push the monorepo when it gets some shape.

**Comment by glensc** [comment]
on sligtly related but off-topic, do you think could merge with @zf1 as i read somewhere @deadbeef84 was okay giving up the repos and the organization. or just not worth the effort (as not clear what's the goal) and the "replace" directives are in place?

**Comment by falkenhawk** [comment]
to be replaced with https://github.com/zf1s/zf1/pull/4

**Pull request closed without merging**
